FT.manifest({
  "filename": "index.html",
  "width": 300,
  "height": 250,
  "clickTagCount": 1,
  "instantAds": [
    { "name": "feedPath", "type": "text", "default": "feeds/uscellular/FBI-4464/stores/" },
    { "name": "imageVersion", "type": "text", "default": "" },
    { "name": "headlineText1", "type": "text", "default": "5G built for<br>Des Moines." },
    { "name": "subheadlineF1", "type": "text", "default": "" },
    { "name": "headlineText2", "type": "text", "default": "Unlimited data for $30 per month." },
    { "name": "subheadlineF2", "type": "text", "default": "Per line with four lines.<br>5G included." },
    { "name": "headlineText3", "type": "text", "default": "Free Samsung Galaxy S21 5G." },
    { "name": "subheadlineF3", "type": "text", "default": "No hidden requirements." },
    { "name": "bgPattern", "type": "image", "default": "images/bgPattern.png" },
    { "name": "bgOfferPattern", "type": "image", "default": "images/bgOfferPattern.png" },
    { "name": "imageFrame1", "type": "image", "default": "images/imageFrame1.png" },
    { "name": "imageFrame1AltText", "type": "text", "default": "Image 1" },
    { "name": "imageFrame2", "type": "image", "default": "images/imageFrame2.png" },
    { "name": "imageFrame2AltText", "type": "text", "default": "Image 2" },
    { "name": "imageFrame3", "type": "image", "default": "images/imageFrame3.png" },
    { "name": "imageFrame3AltText", "type": "text", "default": "Lorena loves a11y" },
    { "name": "logo", "type": "image", "default": "images/logo.png" },
    { "name": "ctaText", "type": "text", "default": "Shop Now" },
    { "name": "ctaColor", "type": "text", "default": "#fc131d" },
    { "name": "bgURL", "type": "text", "default": "http://www.hugeinc.com" },
    { "name": "F1_overwrite_edge_case", "type": "text", "default": "" },
    { "name": "F2_overwrite_edge_case", "type": "text", "default": "" },
    { "name": "F3_overwrite_edge_case", "type": "text", "default": "" },
    { "name": "disclaimerContent", "type": "text", "default": "Promotional pricing requires an Unlimited Everyday or Even Better plan, new line, port-in, credit approval, qualified Smartphone pruchase and comes via monthly bill credit on a 30-mo. RIC. Taxes, fees and additional restriccion apply." }
  ]
});
